# Generated by Django 3.2.11 on 2022-01-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses_Account',
            fields=[
                ('id_account', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID Account')),
                ('ch_name', models.CharField(max_length=100, verbose_name='Name')),
                ('ch_description', models.CharField(max_length=500, verbose_name='Description')),
                ('b_State', models.BooleanField(verbose_name='State')),
                ('dt_Start_Date', models.DateTimeField(verbose_name='Start Date')),
                ('dt_End_Date', models.DateTimeField(verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'db_table': 'tbl_Expenses_Account',
            },
        ),
    ]
