# Generated by Django 3.2.11 on 2022-03-11 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id_expense', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID Expense')),
                ('ch_name', models.CharField(max_length=100, verbose_name='Name')),
                ('ch_description', models.CharField(max_length=500, verbose_name='Description')),
                ('b_State', models.BooleanField(verbose_name='State')),
                ('dt_Start_Date', models.DateTimeField(verbose_name='Start Date')),
                ('fk_expenses_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.expenses_account', verbose_name='FK Expenses')),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
                'db_table': 'tbl_Expenses',
            },
        ),
    ]
